-- Run this in Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

CREATE TABLE IF NOT EXISTS public.rsvps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  name text NOT NULL,
  phone text NOT NULL,
  email text,
  agency text,
  source text DEFAULT 'evento_2_sep'
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.rsvps ENABLE ROW LEVEL SECURITY;

-- Grant required permissions to service_role (fixes error 42501 permission denied)
GRANT ALL ON TABLE public.rsvps TO service_role;
GRANT ALL ON TABLE public.rsvps TO postgres;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
